// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrg1_ZfqVZvWiz5woJ9hFvLcUQEux_F-g',
    appId: '1:654839784013:web:1b125248cc3e848bfd3204',
    messagingSenderId: '654839784013',
    projectId: 'onlineclassapp-ca99a',
    authDomain: 'onlineclassapp-ca99a.firebaseapp.com',
    storageBucket: 'onlineclassapp-ca99a.firebasestorage.app',
    measurementId: 'G-3HVFDHCNZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuv4AHI1NifDv-ZxYE9F4sXoHhC8_GMHI',
    appId: '1:654839784013:android:01edb22c39ad965ffd3204',
    messagingSenderId: '654839784013',
    projectId: 'onlineclassapp-ca99a',
    storageBucket: 'onlineclassapp-ca99a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vp0d_HBD1MUAA6mNVgKsWw6RzLftaJc',
    appId: '1:654839784013:ios:c21bb9e6d8e3a8c7fd3204',
    messagingSenderId: '654839784013',
    projectId: 'onlineclassapp-ca99a',
    storageBucket: 'onlineclassapp-ca99a.firebasestorage.app',
    iosBundleId: 'com.example.onlineclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vp0d_HBD1MUAA6mNVgKsWw6RzLftaJc',
    appId: '1:654839784013:ios:c21bb9e6d8e3a8c7fd3204',
    messagingSenderId: '654839784013',
    projectId: 'onlineclassapp-ca99a',
    storageBucket: 'onlineclassapp-ca99a.firebasestorage.app',
    iosBundleId: 'com.example.onlineclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrg1_ZfqVZvWiz5woJ9hFvLcUQEux_F-g',
    appId: '1:654839784013:web:32fd1c3e2753aa09fd3204',
    messagingSenderId: '654839784013',
    projectId: 'onlineclassapp-ca99a',
    authDomain: 'onlineclassapp-ca99a.firebaseapp.com',
    storageBucket: 'onlineclassapp-ca99a.firebasestorage.app',
    measurementId: 'G-M7TJLLL8CN',
  );
}
